// modal types
export const SUCCESS = "SUCCESS";
export const ERROR = "ERROR";
export const CLEAR = "CLEAR";
// registration types
export const REGISTRATION_START = "REGISTRATION_START";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAIL = "REGISTRATION_FAIL";

// toggle sidebar type
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
// theme
export const CHANGE_THEME = "CHANGE_THEME";
// login
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
// create restaurant
export const CREATE_RESTAURANT_START = "CREATE_RESTAURANT_START";
export const CREATE_RESTAURANT_SUCCESS = "CREATE_RESTAURANT_SUCCESS";
export const CREATE_RESTAURANT_FAIL = "CREATE_RESTAURANT_FAIL";
// get all restaurants
export const GET_ALL_RESTAURANTS_SUCCESS = "GET_ALL_RESTAURANTS_SUCCESS";
export const GET_ALL_RESTAURANTS_FAIL = "GET_ALL_RESTAURANTS_FAIL";
// delete a restaurant
export const DELETE_RESTAURANT_SUCCESS = "DELETE_RESTAURANT_SUCCESS";
export const DELETE_RESTAURANT_FAIL = "DELETE_RESTAURANT_FAIL";
// create food item
export const CREATE_FOOD_START = "CREATE_FOOD_START";
export const CREATE_FOOD_SUCCESS = "CREATE_fOOD_SUCCESS";
export const CREATE_FOOD_FAIL = "CREATE_FOOD_FAIL";
// get all food items
export const GET_ALL_FOOD_SUCCESS = "GET_ALL_FOOD_SUCCESS";
export const GET_ALL_FOOD_FAIL = "GET_ALL_FOOD_FAIL";
// get food items by restaurant id
export const GET_FOOD_BY_RESTAURANT_SUCCESS = "GET_FOOD_BY_RESTAURANT_SUCCESS";
export const GET_FOOD_BY_RESTAURANT_FAIL = "GET_FOOD_BY_RESTAURANT_FAIL";
// update  restaurant
export const UPDATE_RESTAURANT_START = "UPDATE_RESTAURANT_START";
export const UPDATE_RESTAURANT_SUCCESS = "UPDATE_RESTAURANT_SUCCESS";
export const UPDATE_RESTAURANT_FAIL = "UPDATE_RESTAURANT_FAIL";
// get restaurant by id
export const GET_RESTAURANT_SUCCESS = "GET_RESTAURANT_SUCCESS";
export const GET_RESTAURANT_FAIL = "GET_RESTAURANT_FAIL";
// get food item by id
export const GET_FOOD_BY_ID_SUCCESS = "GET_FOOD_BY_ID_SUCCESS";
export const GET_FOOD_BY_ID_FAIL = "GET_FOOD_BY_ID_FAIL";
